package GUI;

import org.json.simple.JSONObject;

import javax.swing.*;
import java.awt.*;

public class Visualization extends JFrame {
    private JPanel panel1;
    private JButton updateButton;
    private JButton addButton;

    public Visualization() {
        JFrame crnt = this;
        setSize(500, 400);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        $$$setupUI$$$();
        panel1.add(new Canvas());
        setContentPane(panel1);
        setVisible(true);

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.NORTH);
        updateButton = new JButton();
        updateButton.setText("Update");
        panel2.add(updateButton, BorderLayout.SOUTH);
        addButton = new JButton();
        addButton.setText("Add");
        panel2.add(addButton, BorderLayout.CENTER);
    }



    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
